# Generated by Django 2.2.3 on 2020-06-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucifermusic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ludifermusic',
            name='name',
            field=models.CharField(default='music', max_length=100),
        ),
    ]
